
//app
export const APP_GET_DISTRICT = 'APP_GET_DISTRICT';
export const SET_CAR_INSURANCE_TYPE = 'SET_CAR_INSURANCE_TYPE'

//login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_WITH_OTP = 'LOGIN_WITH_OTP';
export const CONFIRM_REF_CODE = 'CONFIRM_REF_CODE';

//_________PROFILE
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_GET_INFO_SUCCESS = 'PROFILE_GET_INFO_SUCCESS';
export const LIST_PACKGES_GET_INFO_SUCCESS = 'LIST_PACKGES_GET_INFO_SUCCESS';
export const PROFILE_LIST_CONTRACT_SUCCESS = 'PROFILE_LIST_CONTRACT_SUCCESS';
export const PROFILE_GET_AFFILIATECODE_SUCCESS = 'PROFILE_GET_AFFILIATECODE_SUCCESS';




//---------------buy


export const SAVE_ORDER_INFOMATION = 'SAVE_ORDER_INFOMATION'
export const SAVE_ORDER_ID = 'SAVE_ORDER_ID'

//notify
export const NOTIFY_REQUEST = 'NOTIFY_REQUEST';
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_FAIL = 'NOTIFY_FAIL';

//car
export const CAR_GET_AMOUNT_SUCCESS = 'CAR_GET_AMOUNT_SUCCESS';
export const CAR_REQUIREMENT_REQUEST = 'CAR_REQUIREMENT_REQUEST';
export const CAR_MODAL_CHECK_PRICE = 'CAR_MODAL_CHECK_PRICE';
export const CAR_SET_PATH_CORNER = 'CAR_SET_PATH_CORNER';
export const CAR_EXCLUSION_SUCCESS = 'CAR_EXCLUSION_SUCCESS';
export const CAR_SET_PROFILE_ID = 'CAR_SET_PROFILE_ID';
export const CAR_PACKAGE_REQUEST = 'CAR_PACKAGE_REQUEST';
export const CLOSE_CONTRACT_SUCCESS = 'CLOSE_CONTRACT_SUCCESS';
export const SAVE_CONTRACT_SUCCESS = 'SAVE_CONTRACT_SUCCESS';
export const CAR_CHECK_PRICE_REQUEST = 'CAR_CHECK_PRICE_REQUEST';
export const SET_PRODUCER = 'SET_PRODUCER';
export const CAR_FAIL = 'CAR_FAIL';
export const CAR_REQUEST = 'CAR_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const SET_PRICE = 'SET_PRICE';
export const SET_PRICE_INSO = 'SET_PRICE_INSO';
export const ADD_PRICE = 'ADD_PRICE';
export const ADD_PRICE_INSO = 'ADD_PRICE_INSO';
export const PUSH_PRICE = 'PUSH_PRICE';
export const PUSH_PRICE_INSO = 'PUSH_PRICE_INSO';
export const CAR_UPDATE_IMAGE = 'CAR_UPDATE_IMAGE';
export const CAR_REQUIREMENT_SUCCESS = 'CAR_REQUIREMENT_SUCCESS';
export const CAR_FORM_SUCCESS = 'CAR_FORM_SUCCESS';
export const CAR_PACKAGE_SUCCESS = 'CAR_PACKAGE_SUCCESS';
export const CAR_PACKAGE_FAIL = 'CAR_PACKAGE_FAIL';
export const CAR_YEAR_SUCCESS = 'CAR_YEAR_SUCCESS';
export const CAR_CHECK_PRICE_SUCCESSS = 'CAR_CHECK_PRICE_SUCCESSS';
export const CAR_CHECK_PRICE_FAIL = 'CAR_CHECK_PRICE_FAIL';
export const CAR_GET_PRICE_SUCCESS = 'CAR_GET_PRICE_SUCCESS';

export const CAR_SEAT_SUCCESS = 'CAR_SEAT_SUCCESS';
export const CAR_MODEL_SUCCESS = 'CAR_MODEL_SUCCESS';
export const CAR_PRODUCER_REQUEST = 'CAR_PRODUCER_REQUEST';
export const CAR_PRODUCER_SUCCESS = 'CAR_PRODUCER_SUCCESS';
export const CAR_PRODUCER_FAIL = 'CAR_PRODUCER_FAIL';
export const RESET_DATA = 'RESET_DATA';
export const PRICE_SALE = 'PRICE_SALE';

export const CAR_GET_LIST_BRANCH_SUCCESS = 'CAR_GET_LIST_BRANCH_SUCCESS'
export const CAR_GET_LIST_MODEL_SUCCESS = 'CAR_GET_LIST_MODEL_SUCCESS'
export const CAR_GET_TYPE_SUCCESS = 'CAR_GET_TYPE_SUCCESS'
export const SET_CAR_INFO = 'SET_CAR_INFO'
export const SET_CAR_INSURANCE_BUYER_INFO = 'SET_CAR_INSURANCE_BUYER_INFO'
export const SET_CAR_IMAGE_SUCCESS = 'SET_CAR_IMAGE_SUCCESS'
export const SAVE_IMAGE_CAR_CERTIFICATE = 'SAVE_IMAGE_CAR_CERTIFICATE'
export const SAVE_IMAGE_CAR_REGISTRATION_CERTIFICATE = 'SAVE_IMAGE_CAR_REGISTRATION_CERTIFICATE'
export const REMOVE_CAR_IMAGE_SUCCESS = 'REMOVE_CAR_IMAGE_SUCCESS'
export const SET_PREVIEW_CAR_IMAGE_SUCCESS = 'SET_PREVIEW_CAR_IMAGE_SUCCESS'
export const GET_LIST_PROVINCE_SUCCESS = 'GET_LIST_PROVINCE_SUCCESS'
export const GET_LIST_DISTRICT_SUCCESS = 'GET_LIST_DISTRICT_SUCCESS'
export const CAR_SET_INSURANCE_PACKAGES = 'CAR_SET_INSURANCE_PACKAGES'
export const SET_IMAGE_FILE = 'SET_IMAGE_FILE'


//DELAY FIGHLT
export const FLIGHT_GET_PACKAGE_SUCCESS = 'FLIGHT_GET_PACKAGE_SUCCESS';
export const FLIGHT_LOADING = 'FLIGHT_LOADING';
export const FLIGHT_GET_LIST_SUCCESS = 'FLIGHT_GET_LIST_SUCCESS';
export const FLIGHT_GET_LIST_PACKAGE = 'FLIGHT_GET_LIST_PACKAGE';
export const FLIGHT_GET_LIST_PACKAGE_SUCCESS = 'FLIGHT_GET_LIST_PACKAGE_SUCCESS';
export const FLIGHT_GET_INFO_FLIGHT_SUCCESS = 'FLIGHT_GET_INFO_FLIGHT_SUCCESS';
export const FLIGHT_GET_LIST_FLIGHT_DEPARTURE = 'FLIGHT_GET_LIST_FLIGHT_DEPARTURE';
export const FLIGHT_GET_COUNTRY = 'FLIGHT_GET_COUNTRY';
export const FLIGHT_GET_ARRIVALAIRPORT = 'FLIGHT_GET_ARRIVALAIRPORT';
export const FLIGHT_GET_INTRODUCTION = 'FLIGHT_GET_INTRODUCTION';
export const FLIGHT_CANCAL_OLD_FLIGHT = 'FLIGHT_CANCAL_OLD_FLIGHT';
export const FLIGHT_GET_DEPATUREAIREPORT = 'FLIGHT_GET_DEPATUREAIREPORT';
export const FLIGHT_GET_COUNTRY_ARRIVAL = 'FLIGHT_GET_COUNTRY_ARRIVAL';

export const FLIGHT_SET_CUSTOMERS_INFO = 'FLIGHT_SET_CUSTOMERS_INFO';
export const FLIGHT_SET_FLIGHT_INFO = 'FLIGHT_SET_FLIGHT_INFO'
export const FLIGHT_SET_BILL_INFO = 'FLIGHT_SET_BILL_INFO'
export const FLIGHT_SET_INSURANCE_PACKAGE_INFO = 'FLIGHT_SET_INSURANCE_PACKAGE_INFO';
export const SET_CUSTOM_FLIGHT_INFO = 'SET_CUSTOM_FLIGHT_INFO'
export const SET_CUSTOM_DEPART_FLIGHT = 'SET_CUSTOM_DEPART_FLIGHT';
export const SET_CUSTOM_RETURN_FLIGHT = 'SET_CUSTOM_RETURN_FLIGHT'


export const FLIGHT_GET_GROUP_DOCUMENT = 'FLIGHT_GET_GROUP_DOCUMENT';

//TNDS
export const TNDS_SET_CAR_INFO = 'TNDS_SET_CAR_INFO';
export const TNDS_SET_CUSTOMER_INFO = 'TNDS_SET_CUSTOMER_INFO';
export const TNDS_SET_PACKAGES = 'TNDS_SET_PACKAGES';

//CLAIM FLIGHT
export const FLIGHT_GET_BANKS_SUCCESS = 'FLIGHT_GET_BANKS_SUCCESS';
export const FLIGHT_GET_TARGETS_SUCCESS = 'FLIGHT_GET_TARGETS_SUCCESS';
export const FLIGHT_UPDATE_CLAIM_SUCCESS = 'FLIGHT_UPDATE_CLAIM_SUCCESS';
export const FLIGHT_UPDATE_FORM_PROFILE_SUCCESS = 'FLIGHT_UPDATE_FORM_PROFILE_SUCCESS';
export const CHECK_FLIGHT_ADD_CLAIM = 'CHECK_FLIGHT_ADD_CLAIM';
export const FLIGHT_CLAIM_INFO_SUCCESS = 'FLIGHT_CLAIM_INFO_SUCCESS';


//Travel

export const TRAVEL_GET_PACKAGES = 'TRAVEL_GET_PACKAGES'
export const TRAVEL_SAVE_TOUR_INFO = 'TRAVEL_SAVE_TOUR_INFO'
export const TRAVEL_SAVE_PACKAGE_INFO = 'TRAVEL_SAVE_PACKAGE_INFO'
export const TRAVEL_SAVE_BUYER_INFO = 'TRAVEL_SAVE_BUYER_INFO'
export const TRAVEL_SAVE_INSURED_CUSTOMER_INFO = 'TRAVEL_SAVE_INSURED_CUSTOMER_INFO'
export const TRAVEL_SAVE_INSURED_TYPE = 'TRAVEL_SAVE_INSURED_TYPE'

//house
export const HOUSE_SAVE_HOUSE_INFO = 'HOUSE_SAVE_HOUSE_INFO';
export const HOUSE_SAVE_BUYER_INFO = 'HOUSE_SAVE_BUYER_INFO';
export const HOUSE_SAVE_INSURANCE_PRINT_ADDRESS = 'HOUSE_SAVE_INSURANCE_PRINT_ADDRESS';
export const HOUSE_SAVE_INSURED_CUSTOMER = 'HOUSE_SAVE_INSURANCE_PRINT_ADDRESS';
export const HOUSE_SAVE_VAT_INFO = 'HOUSE_SAVE_VAT_INFO';
export const HOUSE_SAVE_HOUSE_TYPE = 'HOUSE_SAVE_HOUSE_TYPE';
export const HOUSE_SAVE_HOUSE_PROPERTY_INSURANCE = 'HOUSE_SAVE_HOUSE_PROPERTY_INSURANCE';

//Accident
export const RESET_DATA_ACCIDENT = 'RESET_DATA_ACCIDENT';
export const ACCIDENT_SET_PACKAGES_INFO = 'ACCIDENT_SET_PACKAGES_INFO';
export const ACCIDENT_SET_PACKAGES = 'ACCIDENT_SET_PACKAGES';
export const ACCIDENT_SAVE_CHOSEN_PACKAGE = 'ACCIDENT_SAVE_CHOSEN_PACKAGE';
export const ACCIDENT_SAVE_BUYER_INFO = 'ACCIDENT_SAVE_BUYER_INFO';
export const ACCIDENT_SAVE_BUYER_AAA = 'ACCIDENT_SAVE_BUYER_AAA';
export const ACCIDENT_SAVE_CUSTOMER_AAA = 'ACCIDENT_SAVE_CUSTOMER_AAA';
export const ACCIDENT_SAVE_INSURED_CUSTOMER_INFO = 'ACCIDENT_SAVE_INSURED_CUSTOMER_INFO';
export const ACCIDENT_SAVE_INSURANCE_PRINT_ADDRESS = 'ACCIDENT_SAVE_INSURANCE_PRINT_ADDRESS';
export const ACCIDENT_SAVE_VAT_INFOMATION = 'ACCIDENT_SAVE_VAT_INFOMATION';

//Motor
export const RESET_DATA_MOTOR = 'RESET_DATA_MOTOR';
export const TNDS_SET_MOTOR_TYPE = 'TNDS_SET_MOTOR_TYPE'
export const TNDS_SET_MOTOR_DURATION = 'TNDS_SET_MOTOR_DURATION'
export const SAVE_MOTOR_BUYER = 'SAVE_MOTOR_BUYER'
export const SAVE_FEE_MOTOR = 'SAVE_FEE_MOTOR'
export const SAVE_IMG_OCR = 'SAVE_IMG_OCR'
export const SAVE_BODY_CONTRACT_MOTOR = 'SAVE_BODY_CONTRACT_MOTOR'

//MotorPhysical
export const MOTOR_GET_LIST_BRAND_SUCCESS = 'MOTOR_GET_LIST_BRAND_SUCCESS'
export const MOTOR_GET_LIST_MODEL_SUCCESS = 'MOTOR_GET_LIST_MODEL_SUCCESS'
export const SET_MOTOR_TYPE_PHYSICAL = 'SET_MOTOR_TYPE_PHYSICAL'
export const SAVE_IMG_OCR_PHYSICAL = 'SAVE_IMG_OCR_PHYSICAL'
export const SAVE_MOTOR_BUYER_PHYSICAL = 'SAVE_MOTOR_BUYER_PHYSICAL'
export const RESET_DATA_MOTOR_PHYSICAL = 'RESET_DATA_MOTOR_PHYSICAL'

//tnds car
export const TNDS_SET_CAR_TYPE = 'TNDS_SET_CAR_TYPE'
export const SAVE_CAR_BUYER = 'SAVE_CAR_BUYER'
export const SAVE_FEE_TNDSCAR = 'SAVE_FEE_TNDSCAR'
export const SAVE_FEE_LXPXCAR = 'SAVE_FEE_LXPXCAR'
export const TNDS_SET_CAR_DURATION = 'TNDS_SET_CAR_DURATION'
export const SAVE_IMG_OCR_CAR = 'SAVE_IMG_OCR_CAR'
export const CHECK_OCR_AGAIN = 'CHECK_OCR_AGAIN'
export const RESET_DATA_CAR = 'RESET_DATA_CAR'


//params contract
export const SAVE_PARAMS_CONTRACT = 'SAVE_PARAMS_CONTRACT'

//commissions
export const COMMISSIONS_SET_INFORMATION = 'COMMISSIONS_SET_INFORMATION'
export const COMMISSIONS_SET_LIST = 'COMMISSIONS_SET_LIST'
export const COMMISSIONS_SET_TOTAL_FULL = 'COMMISSIONS_SET_TOTAL_FULL'

//promotions
export const PROMOTION_SET_INFO = 'PROMOTION_SET_INFO'
export const PROMOTION_SET_PRICE = 'PROMOTION_SET_PRICE'

//insurance
export const INSURANCE_SET_INFO = 'INSURANCE_SET_INFO'
export const SET_PERMISSION_USER = 'SET_PERMISSION_USER'
export const SET_TOKEN_INSUR = 'SET_TOKEN_INSUR'

//kpis
export const KPI_SET_INFO = 'KPI_SET_INFO'

//contracts
export const CONTRACT_SET_INFORMATION = 'CONTRACT_SET_INFORMATION'
export const SET_DETAIL_CONTRACT = 'SET_DETAIL_CONTRACT'
export const SET_EDIT_CONTRACT = 'SET_EDIT_CONTRACT'
export const SET_LIST_REGIS_ACC = 'SET_LIST_REGIS_ACC'

//Car_Physical
export const SET_CAR_PHYSICAL_TYPE = 'SET_CAR_PHYSICAL_TYPE'
export const SAVE_IMG_CAR_PHYSICAL = 'SAVE_IMG_CAR_PHYSICAL'
export const CHECK_OCR_AGAIN_PHYSICAL = 'CHECK_OCR_AGAIN_PHYSICAL'
export const SAVE_CAR_BUYER_PHYSICAL = 'SAVE_CAR_BUYER_PHYSICAL'
export const CHANG_DATA_PACKAGE = 'CHANG_DATA_PACKAGE'
export const RESET_DATA_CAR_PHYSICAL = 'RESET_DATA_CAR_PHYSICAL'
export const SAVE_CONTRACT_CAR_ID = 'SAVE_CONTRACT_CAR_ID'

//Payment_Method
export const PAYMENT_METHOD_SET_INFORMATION = 'PAYMENT_METHOD_SET_INFORMATION'
export const PAYMENT_METHOD_SET_BANK_INFORMATION = 'PAYMENT_METHOD_SET_BANK_INFORMATION'

//House_Insurance
export const SET_HOUSE_PACKAGES = 'SET_HOUSE_PACKAGES'
export const SAVE_BUYER_HOUSE = 'SAVE_BUYER_HOUSE'
export const RESET_DATA_HOUSE = 'RESET_DATA_HOUSE'

//Travel_Insurance
export const SET_INFO_TRAVEL = 'SET_INFO_TRAVEL'
export const SET_TRAVEL_PACKAGES = 'SET_TRAVEL_PACKAGES'
export const SAVE_BUYER_TRAVEL = 'SAVE_BUYER_TRAVEL'
export const RESET_DATA_TRAVEL = 'RESET_DATA_TRAVEL'
export const SAVE_SELL_INFO = 'SAVE_SELL_INFO'

//Delay_Flight
export const SET_INFO_DELAY_FLIGHT = 'SET_INFO_DELAY_FLIGHT'
export const SET_DELAY_FLIGHT_PACKAGES = 'SET_DELAY_FLIGHT_PACKAGES'
export const SAVE_BUYER_DELAY_FLIGHT = 'SAVE_BUYER_DELAY_FLIGHT'
export const SET_CODE_NUMBER = 'SET_CODE_NUMBER'
export const RESET_DATA_DELAY_FLIGHT = 'RESET_DATA_DELAY_FLIGHT'

//Select_Company
export const SET_INFO_LIST_COMPANY = 'SET_INFO_LIST_COMPANY'
export const SET_ID_COM_SELECTED = 'SET_ID_COM_SELECTED'

//Compensation
export const COMPENSATION_SET_INFORMATION = 'COMPENSATION_SET_INFORMATION'

//Notify
export const NOTIFY_SET_INFORMATION = 'NOTIFY_SET_INFORMATION'

//VTA
export const VTA_SET_PACKAGES_INFO = 'VTA_SET_PACKAGES_INFO';
export const VTA_SET_PACKAGES = 'VTA_SET_PACKAGES';
export const VTA_SAVE_CHOSEN_PACKAGE = 'VTA_SAVE_CHOSEN_PACKAGE';
export const VTA_SAVE_BUYER_INFO = 'VTA_SAVE_BUYER_INFO';
export const VTA_SAVE_INSURED_CUSTOMER_INFO = 'VTA_SAVE_INSURED_CUSTOMER_INFO';
export const VTA_SAVE_INSURANCE_PRINT_ADDRESS = 'VTA_SAVE_INSURANCE_PRINT_ADDRESS';
export const VTA_SAVE_VAT_INFOMATION = 'VTA_SAVE_VAT_INFOMATION';
export const SAVE_IMG_OCR_VTA = 'SAVE_IMG_OCR_VTA';
export const RESET_DATA_VTA = 'RESET_DATA_VTA';

//Log_Contract
export const SET_LOG_CONTRACT = 'SET_LOG_CONTRACT'

//ASML
export const SET_PACKAGES_INFO_24H = 'SET_PACKAGES_INFO_24H';
export const SAVE_CHOSEN_PACKAGE_24H = 'SAVE_CHOSEN_PACKAGE_24H';
export const SAVE_BUYER_INFO_24H = 'SAVE_BUYER_INFO_24H';
export const SAVE_INSURED_CUSTOMER_INFO_24H = 'SAVE_INSURED_CUSTOMER_INFO_24H';
export const SAVE_INSURANCE_PRINT_ADDRESS_24H = 'SAVE_INSURANCE_PRINT_ADDRESS_24H';
export const SAVE_IMG_OCR_24H = 'SAVE_IMG_OCR_24H';
export const RESET_DATA_24H = 'RESET_DATA_24H';

//User
export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const SET_PROFILE_LOG = 'SET_PROFILE_LOG';
export const SET_TPBANK_LOG = 'SET_TPBANK_LOG';
export const SET_TPBANK_INFO_IMG = 'SET_TPBANK_INFO_IMG';
export const SET_FMARKET_LOG = 'SET_FMARKET_LOG';
export const GET_LIST_BANK_SUCCESS = 'GET_LIST_BANK_SUCCESS';
export const GET_LIST_NATION_SUCCESS = 'GET_LIST_NATION_SUCCESS';
export const SET_PROFILE_INFORMATION = 'SET_PROFILE_INFORMATION';
export const SET_ORG_CODE_USER = 'SET_ORG_CODE_USER';
export const SET_LEVEL_USER = 'SET_LEVEL_USER';

//revenue
export const REVENUE_SET_LIST = 'REVENUE_SET_LIST'

//accountGroup
export const GET_LIST_REFERRAL_ACC = 'GET_LIST_REFERRAL_ACC'

//VBIACare
export const ACARE_SAVE_BUYER_INFO = 'ACARE_SAVE_BUYER_INFO'
export const ACARE_SAVE_IMG_OCR = 'ACARE_SAVE_IMG_OCR'
export const ACARE_SAVE_CUSTOMER_INFO = 'ACARE_SAVE_CUSTOMER_INFO'
export const ACARE_SAVE_PACKAGE_INFO = 'ACARE_SAVE_PACKAGE_INFO'
export const RESET_DATA_ACARE = 'RESET_DATA_ACARE'